### PR TITLE
Fix console entry point to allow direct execution with uvx

### PR DESCRIPTION
**Pull request by amitness**
Hi @koaning,

Currently, when trying to use bulk with `uvx` directly:

```python
uvx bulk text df.csv
```

It raises this **error**:

```bash
Traceback (most recent call last):
  File "/Users/amitness/Library/Caches/uv/archive-v0/Ai18k3ieJ7bpU38lhPOKc/bin/bulk", line 7, in <module>
    from bulk.__main__ import app
ImportError: cannot import name 'app' from 'bulk.__main__' (/Users/amitness/Library/Caches/uv/archive-v0/Ai18k3ieJ7bpU38lhPOKc/lib/python3.8/site-packages/bulk/__main__.py)
```

But, if you run it as a module, it works as usual because that doesn't invoke the console script.
```
python -m bulk text df.csv
```

I found that the reason is because the entrypoint defined in `console_scripts` is wrong and still set to the typer app. While the code has switched to click for the command line parsing. 

I have pushed a fix for this. As such, both the scripts below will work now.

```
bulk text df.csv
uvx bulk text df.csv
```

You can also test my changes via this command using `df.csv` from [here](https://github.com/koaning/bulk/blob/main/utils/df.csv)
```
uvx --from=git+https://github.com/amitness/bulk@fix-uvx bulk text df.csv
```

### CODE REVIEW

**Comment by koaning** [comment]
Hey I remember that name! Back when I worked at Rasa I recall reading your blog a bunch, nice to see you here.

**Review by koaning — APPROVED** [review]
Yeah, these changes look fair to me. When I made this tool it was well before the big `uv` ecosystem releases. Thanks for the addition!

**Comment by koaning** [comment]
Ah it seems that the unit tests break due to an issue on my side. I think if you pull from main it should turn green.

**Comment by amitness** [comment]
@koaning Thank you, I have synced with main, should work now

And, glad to hear you remember :) 

This [video](https://youtu.be/HEGaei7k0zE?list=PLgIaq8VgndJtZ_G6gxyuhHGLUy9zXV9JC&t=2040) discussing tools for exploring LLM prompts actually sent me here

**Comment by koaning** [comment]
Ah yeah, that was a popular demo.

**Pull request merged**
